### PR TITLE
Improve Localisation

### PR DESCRIPTION
**Pull request by tpreusse**
Goals
1. Ensure UI is in the selected locale
2. Allow the user to read the terms of service in their own language

pac

Under the hood changes:
- replace `getMessage` with a custom implementation
  it is not possible to set the locale with getMessage
  https://bugs.chromium.org/p/chromium/issues/detail?id=660704
- adapt wording of `language_instructions` message
  I removed the Danish and Italian message for the time being (now falls back to the updated English message)
- fix / add missing messages (`terms_of_service_accept`, `language`, `country`)
- fix formatting in German `terms_of_service` messages

### CODE REVIEW

**Comment by thejefflarson** [comment]
On first glance, this looks great! I’ll take a deeper look and merge it in
on Monday. Thanks!

**Comment by tpreusse** [comment]
Awesome.

I further improved the German and Swiss German translation and added a i18n & l10n section to the readme.

The toggle labels now look cleaner and should be more understandable in German:
screen shot 2017-11-26 at 18 12 02

**Comment by tpreusse** [comment]
I noticed that you load country names in `['fr', 'fi', 'nl', 'sv']` which do not have translated messages:
https://github.com/propublica/facebook-political-ads/pull/17/files#diff-31f285a1779d40d5c8d386d9addae424R12

I left them in for now. Maybe their countries should also be marked as active in `i18n.js`.

**Comment by thejefflarson** [comment]
I don't think we need to mark their countries as active just yet -- we don't have translations for them  or news partners just yet so it would be a waste. I originally included them because there was some interest in joining up, so we'll just leave it as is. 

I'm loving this pull request, a couple cool things I especially like:

[This](https://github.com/republik/facebook-political-ads/blob/fa37264559e189065fb88df399701c63f17a87fe/extension/src/i18n.js#L25) `reduceRight` trick is very cool.

And I didn't realize you could do stuff like [this](https://github.com/republik/facebook-political-ads/blob/fa37264559e189065fb88df399701c63f17a87fe/extension/src/i18n.js#L49) with `connect` but now that I see it in action it makes total sense.

Thanks you again for doing this! It really looks like a better user experience.

**Comment by tpreusse** [comment]
It was a pleasure. The repo setup is super smooth. I love the simplicity of the extension—makes it easy and very enjoyable to work on.

Great work, thank you.

Looking forward to seeing this in action.

**Pull request merged**
