### PR TITLE
Refactor server-side test code

### PR DESCRIPTION
**Pull request by bsmithgall**
This PR makes a change to break out the server-side tests into specific `unit` and `integration` tests by introducing a new `tests` directory and moving the tests that require the database there. It also adds additional utilities for setting up a test database, and making sure that the server side tests pass after a fresh `git clone`.

The actual code is almost entirely unchanged in this PR. The only actual change is to make `parse_targeting` a public function so that it can be accessed by the tests.

This PR also introduces a dependency on the [rand](https://crates.io/crates/rand) crate to help with some test methods.

Inspired by this comment in the README:

> In general, the project needs more tests. We've written a couple of tests for parsing the Facebook timeline in the extension directory, and a few for the tricky bits in the server, but any help here would be great!

---

NOTES:

+ I had some trouble getting the extension tests to pass out of the box. Running `npm install` followed by `npm test` gave me a `ReferenceError: window is not defined`. I would be happy to do some additional work to add a more robust testing harness like Jasmine or Mocha but would want to get feedback from the maintainers before going in that direction. It's possible I missed a setup step.
+ I am not super familiar with Rust, so these changes are based almost entirely on what I could find from read the rust book. Happy to make changes if there are more idiomatic ways to do things that I don't know. There were also a few things I couldn't figure out how to do, like creating a `vec` of `NewAd`s to insert into the database. It would also be good if there was a way to run the tests in parallel somehow.

### CODE REVIEW

**Comment by thejefflarson** [comment]
This is very cool! Thank you! This is a huge help!

I think you could do something like `vec![AdPost, AdPost, AdPost].iter().map(|p| NewAd(&p, "en-US".to_string()).unwrap()).map(|p| /* your diesel code */).collect();` But the way you have it is fine for now. I also am going to set up routine dumps of the database in a couple days so we can do tests across the whole range of ads, which will be good for the targeting parser tests.

I would love a test harness for the extension tests -- they worked at one time but I don't think they do anymore, and I've been largely flying blind there. The extension will need a lot of mocking and stubbing of facebook behaviors, especially in the way we grab the targeting parameters. Which could get crazy fast.

Appreciate that someone noticed that note!

**Comment by bsmithgall** [comment]
Cool -- I have some additional time tomorrow so I can explore testing extension side tomorrow. Both [jasmine](https://jasmine.github.io/) and mocha with [sinon](http://sinonjs.org/) have good mocking capabilities so I might explore using one of those. There's also [jest](https://facebook.github.io/jest/) but I don't know how well it works with preact vs. react.

**Comment by bsmithgall** [comment]
Hey @thejefflarson just wanted to follow up with this -- I poked around with setting something up with Jest and it was somewhat promising, but I couldn't get it to work without really changing the `parser.js` internals because it returns a number of promises. I couldn't figure out entirely how to get the mocking to work without refactoring the source, and I didn't want to change that too much.

**Comment by thejefflarson** [comment]
I was worried about that, let me see if I can detangle parser.js, I have a tracking issue [here](https://github.com/propublica/facebook-political-ads/issues/24). I'll dive into breaking it apart. Thanks for looking though!

**Pull request merged**
